USE ROLE ACCOUNTADMIN;
USE DATABASE ZOMATO_DWH;
USE SCHEMA UTIL;

CREATE OR REPLACE TABLE PROC_AUDIT_LOG (
  PROC_NAME   STRING,
  RUN_TS      TIMESTAMP_NTZ,
  STATUS      STRING,
  MESSAGE     STRING
);
