USE ROLE ACCOUNTADMIN;
USE DATABASE ZOMATO_DWH;
USE SCHEMA UTIL;

CREATE OR REPLACE FUNCTION FN_DELIVERY_SLA_BUCKET(
  ESTIMATED_TIME_MIN NUMBER,
  ACTUAL_TIME_MIN    NUMBER
)
RETURNS STRING
LANGUAGE SQL
AS
$$
CASE
  WHEN ACTUAL_TIME_MIN IS NULL THEN 'UNKNOWN'
  WHEN ACTUAL_TIME_MIN <= ESTIMATED_TIME_MIN THEN 'ON_TIME'
  WHEN ACTUAL_TIME_MIN <= ESTIMATED_TIME_MIN + 10 THEN 'SLIGHT_DELAY'
  ELSE 'HEAVY_DELAY'
END
$$;
