USE ROLE ACCOUNTADMIN;
USE DATABASE ZOMATO_DWH;
USE SCHEMA UTIL;

CREATE OR REPLACE MASKING POLICY MP_EMAIL_MASK
AS (VAL STRING) RETURNS STRING ->
  CASE
    WHEN CURRENT_ROLE() IN ('ZOMATO_PII_ADMIN_ROLE','ACCOUNTADMIN') THEN VAL
    ELSE REGEXP_REPLACE(VAL, '(^.).*(@.*$)', '\\1*****\\2')
  END;

CREATE OR REPLACE MASKING POLICY MP_PHONE_MASK
AS (VAL STRING) RETURNS STRING ->
  CASE
    WHEN CURRENT_ROLE() IN ('ZOMATO_PII_ADMIN_ROLE','ACCOUNTADMIN') THEN VAL
    ELSE CONCAT('XXXXXX', RIGHT(VAL, 4))
  END;
