USE ROLE ACCOUNTADMIN;
USE DATABASE ZOMATO_DWH;
USE SCHEMA UTIL;

CREATE OR REPLACE TABLE RLS_USER_ACCESS (
  USER_NAME     STRING,
  ACCESS_TYPE   STRING,      -- 'CITY' or 'RESTAURANT'
  CITY          STRING,
  RESTAURANT_ID NUMBER
);
