USE ROLE ACCOUNTADMIN;
USE DATABASE ZOMATO_DWH;
USE SCHEMA INT;

ALTER TABLE DIM_CUSTOMER
  MODIFY COLUMN EMAIL SET MASKING POLICY UTIL.MP_EMAIL_MASK;

ALTER TABLE DIM_CUSTOMER
  MODIFY COLUMN PRIMARY_PHONE SET MASKING POLICY UTIL.MP_PHONE_MASK;
