USE DATABASE ZOMATO_DWH;
USE SCHEMA INT;

CREATE OR REPLACE TABLE DIM_DELIVERY_AGENT (
  AGENT_ID           NUMBER,
  AGENT_NAME         STRING,
  PHONE              STRING,
  HIRE_DATE          TIMESTAMP_NTZ,
  CITY               STRING,
  VEHICLE_TYPE       STRING,
  STATUS             STRING
);
