USE ROLE ACCOUNTADMIN;
USE DATABASE ZOMATO_DWH;
USE SCHEMA INT;

CREATE OR REPLACE TABLE DIM_DATE (
  DATE_KEY           NUMBER,
  FULL_DATE          DATE,
  YEAR               NUMBER(4,0),
  MONTH              NUMBER(2,0),
  MONTH_SHORT        STRING,
  DAY_OF_MONTH       NUMBER(2,0),
  DAY_OF_WEEK        NUMBER(2,0),
  DAY_OF_WEEK_SHORT  STRING,
  WEEK_OF_YEAR       NUMBER(2,0)
);
