USE DATABASE ZOMATO_DWH;
USE SCHEMA INT;

CREATE OR REPLACE TABLE DIM_RESTAURANT_SCD3 (
  RESTAURANT_ID        NUMBER,
  RESTAURANT_NAME      STRING,
  CURRENT_CUISINE      STRING,
  PREVIOUS_CUISINE     STRING,
  LAST_CHANGE_DATE     TIMESTAMP_NTZ,
  CITY                 STRING,
  AREA                 STRING
);
