USE DATABASE ZOMATO_DWH;
USE SCHEMA INT;

CREATE OR REPLACE TABLE DIM_PROMOTION (
  PROMO_ID           NUMBER,
  PROMO_CODE         STRING,
  DISCOUNT_PERCENT   NUMBER(5,2),
  START_DATE         TIMESTAMP_NTZ,
  END_DATE           TIMESTAMP_NTZ,
  MAX_DISCOUNT_AMT   NUMBER(10,2),
  TARGET_SEGMENT     STRING,
  TARGET_CITY        STRING
);
