USE DATABASE ZOMATO_DWH;
USE SCHEMA INT;

CREATE OR REPLACE TABLE DIM_CUSTOMER (
  CUSTOMER_SK        NUMBER AUTOINCREMENT,
  CUSTOMER_ID        NUMBER,
  CUSTOMER_NAME      STRING,
  EMAIL              STRING,
  PRIMARY_PHONE      STRING,
  CITY               STRING,
  AREA               STRING,
  SEGMENT            STRING,
  IS_PRIME_MEMBER    BOOLEAN,
  STATUS             STRING,
  EFFECTIVE_FROM     TIMESTAMP_NTZ,
  EFFECTIVE_TO       TIMESTAMP_NTZ,
  IS_CURRENT         BOOLEAN,
  RECORD_SOURCE      STRING
);
