USE DATABASE ZOMATO_DWH;
USE SCHEMA INT;

CREATE OR REPLACE TABLE DIM_RESTAURANT (
  RESTAURANT_SK      NUMBER AUTOINCREMENT,
  RESTAURANT_ID      NUMBER,
  RESTAURANT_NAME    STRING,
  CUISINE_PRIMARY    STRING,
  CUISINE_SECONDARY  STRING,
  CITY               STRING,
  AREA               STRING,
  AVG_RATING         FLOAT,
  COMMISSION_RATE    FLOAT,
  IS_ACTIVE          BOOLEAN,
  ONBOARDED_AT       TIMESTAMP_NTZ,
  EFFECTIVE_FROM     TIMESTAMP_NTZ,
  EFFECTIVE_TO       TIMESTAMP_NTZ,
  IS_CURRENT         BOOLEAN,
  RECORD_SOURCE      STRING
);
