USE DATABASE ZOMATO_DWH;
USE SCHEMA STG;

CREATE OR REPLACE VIEW V_DELIVERY_AGENT_STG AS
SELECT
  TRY_TO_NUMBER(AGENT_ID)     AS AGENT_ID,
  TRIM(AGENT_NAME)            AS AGENT_NAME,
  REGEXP_REPLACE(PHONE,'[^0-9]','') AS PHONE,
  TRY_TO_TIMESTAMP_NTZ(HIRE_DATE) AS HIRE_DATE,
  NULLIF(TRIM(CITY),'')       AS CITY,
  TRIM(VEHICLE_TYPE)          AS VEHICLE_TYPE,
  COALESCE(NULLIF(TRIM(STATUS),''),'ACTIVE') AS STATUS
FROM RAW.RAW_DELIVERY_AGENT;
