USE DATABASE ZOMATO_DWH;
USE SCHEMA STG;

CREATE OR REPLACE VIEW V_PROMOTION_STG AS
SELECT
  TRY_TO_NUMBER(PROMO_ID)     AS PROMO_ID,
  TRIM(PROMO_CODE)            AS PROMO_CODE,
  COALESCE(TRY_TO_NUMBER(DISCOUNT_PERCENT),0) AS DISCOUNT_PERCENT,
  TRY_TO_TIMESTAMP_NTZ(START_DATE) AS START_DATE,
  TRY_TO_TIMESTAMP_NTZ(END_DATE)   AS END_DATE,
  COALESCE(TRY_TO_NUMBER(MAX_DISCOUNT_AMT),0) AS MAX_DISCOUNT_AMT,
  TRIM(TARGET_SEGMENT)        AS TARGET_SEGMENT,
  TRIM(TARGET_CITY)           AS TARGET_CITY
FROM RAW.RAW_PROMOTION;
