USE DATABASE ZOMATO_DWH;
USE SCHEMA INT;

CREATE OR REPLACE TABLE FCT_CUSTOMER_EVENT (
  EVENT_ID        NUMBER,
  CUSTOMER_ID     NUMBER,
  EVENT_TYPE      STRING,
  EVENT_TS        TIMESTAMP_NTZ,
  SEARCH_QUERY    STRING,
  DEVICE_OS       STRING,
  APP_VERSION     STRING
);
