USE DATABASE ZOMATO_DWH;
USE SCHEMA INT;

CREATE OR REPLACE TABLE FCT_ORDER_ENHANCED (
  ORDER_ID             NUMBER,
  CUSTOMER_ID          NUMBER,
  RESTAURANT_ID        NUMBER,
  ORDER_DATE_KEY       NUMBER,
  ORDER_STATUS         STRING,
  PAYMENT_METHOD       STRING,
  PROMO_ID             NUMBER,
  ORDER_SUBTOTAL       NUMBER(12,2),
  ORDER_DISCOUNT       NUMBER(12,2),
  DELIVERY_FEE         NUMBER(10,2),
  TOTAL_AMOUNT         NUMBER(12,2),
  NET_FOOD_AMOUNT      NUMBER(12,2),
  DISCOUNT_PCT         FLOAT,
  SLA_BREACHED         NUMBER,
  PLATFORM_COMMISSION  NUMBER(12,2),
  RESTAURANT_PAYOUT    NUMBER(12,2),
  END_TO_END_MIN       NUMBER,
  IS_DELIVERED         NUMBER,
  IS_CANCELLED         NUMBER
);
