USE DATABASE ZOMATO_DWH;
USE SCHEMA INT;

CREATE OR REPLACE TABLE FCT_FEEDBACK (
  FEEDBACK_ID        NUMBER,
  ORDER_ID           NUMBER,
  CUSTOMER_ID        NUMBER,
  RATING             NUMBER,
  COMMENT            STRING,
  SENTIMENT_SCORE    FLOAT,
  CREATED_AT         TIMESTAMP_NTZ
);
