USE DATABASE ZOMATO_DWH;
USE SCHEMA INT;

CREATE OR REPLACE TABLE FCT_DELIVERY (
  TRIP_ID            NUMBER,
  ORDER_ID           NUMBER,
  AGENT_ID           NUMBER,
  PICKUP_TIME        TIMESTAMP_NTZ,
  DROP_TIME          TIMESTAMP_NTZ,
  DISTANCE_KM        NUMBER(10,2),
  ESTIMATED_TIME_MIN NUMBER,
  ACTUAL_TIME_MIN    NUMBER,
  SLA_BREACH_FLAG    NUMBER
);
