USE DATABASE ZOMATO_DWH;
USE SCHEMA INGESTION;

CREATE OR REPLACE PIPE pipe_order_item
AS
COPY INTO RAW.RAW_ORDER_ITEM
FROM @zomato_internal_stage/order_item
FILE_FORMAT = (FORMAT_NAME = 'zomato_csv_ff')
ON_ERROR = 'CONTINUE';

ALTER PIPE pipe_order_item REFRESH;

SELECT COUNT(*) FROM RAW.RAW_ORDER_ITEM;
SELECT * FROM RAW.RAW_ORDER_ITEM LIMIT 10;

USE SCHEMA RAW;
SELECT *
FROM TABLE(
  INFORMATION_SCHEMA.COPY_HISTORY(
    TABLE_NAME => 'RAW_ORDER_ITEM',
    START_TIME => DATEADD(hour,-1,CURRENT_TIMESTAMP())
);
