USE DATABASE ZOMATO_DWH;
USE SCHEMA INGESTION;

CREATE OR REPLACE PIPE pipe_delivery_agent
AS
COPY INTO RAW.RAW_DELIVERY_AGENT
FROM @zomato_internal_stage/delivery_agent
FILE_FORMAT = (FORMAT_NAME = 'zomato_csv_ff')
ON_ERROR = 'CONTINUE';

ALTER PIPE pipe_delivery_agent REFRESH;

SELECT COUNT(*) FROM RAW.RAW_DELIVERY_AGENT;
SELECT * FROM RAW.RAW_DELIVERY_AGENT LIMIT 10;

USE SCHEMA RAW;
SELECT *
FROM TABLE(
  INFORMATION_SCHEMA.COPY_HISTORY(
    TABLE_NAME => 'RAW_DELIVERY_AGENT',
    START_TIME => DATEADD(hour,-1,CURRENT_TIMESTAMP())
);
