USE DATABASE ZOMATO_DWH;
USE SCHEMA INGESTION;

CREATE OR REPLACE PIPE pipe_delivery_trip
AS
COPY INTO RAW.RAW_DELIVERY_TRAP
FROM @zomato_internal_stage/delivery_trip
FILE_FORMAT = (FORMAT_NAME = 'zomato_csv_ff')
ON_ERROR = 'CONTINUE';

ALTER PIPE pipe_delivery_trip REFRESH;

SELECT COUNT(*) FROM RAW.RAW_DELIVERY_TRAP;
SELECT * FROM RAW.RAW_DELIVERY_TRAP LIMIT 10;

USE SCHEMA RAW;
SELECT *
FROM TABLE(
  INFORMATION_SCHEMA.COPY_HISTORY(
    TABLE_NAME => 'RAW_DELIVERY_TRAP',
    START_TIME => DATEADD(hour,-1,CURRENT_TIMESTAMP())
);
