USE DATABASE ZOMATO_DWH;
USE SCHEMA INGESTION;

CREATE OR REPLACE PIPE pipe_promotion
AS
COPY INTO RAW.RAW_PROMOTION
FROM @zomato_internal_stage/promotion
FILE_FORMAT = (FORMAT_NAME = 'zomato_csv_ff')
ON_ERROR = 'CONTINUE';

ALTER PIPE pipe_promotion REFRESH;

SELECT COUNT(*) FROM RAW.RAW_PROMOTION;
SELECT * FROM RAW.RAW_PROMOTION LIMIT 10;

USE SCHEMA RAW;
SELECT *
FROM TABLE(
  INFORMATION_SCHEMA.COPY_HISTORY(
    TABLE_NAME => 'RAW_PROMOTION',
    START_TIME => DATEADD(hour,-1,CURRENT_TIMESTAMP())
);
