USE DATABASE ZOMATO_DWH;
USE SCHEMA INGESTION;

CREATE OR REPLACE PIPE pipe_customer
AS
COPY INTO RAW.RAW_CUSTOMER
FROM @zomato_internal_stage/customer
FILE_FORMAT = (FORMAT_NAME = 'zomato_csv_ff')
ON_ERROR = 'CONTINUE';

ALTER PIPE pipe_customer REFRESH;

SELECT COUNT(*) FROM RAW.RAW_CUSTOMER;
SELECT * FROM RAW.RAW_CUSTOMER;

USE SCHEMA RAW;
SELECT *
FROM TABLE(
  INFORMATION_SCHEMA.COPY_HISTORY(
    TABLE_NAME => 'RAW_CUSTOMER',
    START_TIME => DATEADD(hour,-1,CURRENT_TIMESTAMP())
);
