USE DATABASE ZOMATO_DWH;
USE SCHEMA INGESTION;

CREATE OR REPLACE PIPE pipe_customer_events
AS
COPY INTO RAW.RAW_CUSTOMER_EVENTS
FROM @zomato_internal_stage/customer_events
FILE_FORMAT = (FORMAT_NAME = 'zomato_json_ff')
ON_ERROR = 'CONTINUE';

ALTER PIPE pipe_customer_events REFRESH;

SELECT COUNT(*) FROM RAW.RAW_CUSTOMER_EVENTS;
SELECT EVENT_RAW FROM RAW.RAW_CUSTOMER_EVENTS LIMIT 10;

USE SCHEMA RAW;
SELECT *
FROM TABLE(
  INFORMATION_SCHEMA.COPY_HISTORY(
    TABLE_NAME => 'RAW_CUSTOMER_EVENTS',
    START_TIME => DATEADD(hour,-1,CURRENT_TIMESTAMP())
);
