USE DATABASE ZOMATO_DWH;
USE SCHEMA INGESTION;

CREATE OR REPLACE PIPE pipe_menu_item
AS
COPY INTO RAW.RAW_MENU_ITEM
FROM @zomato_internal_stage/menu_item
FILE_FORMAT = (FORMAT_NAME = 'zomato_csv_ff')
ON_ERROR = 'CONTINUE';

ALTER PIPE pipe_menu_item REFRESH;

SELECT COUNT(*) FROM RAW.RAW_MENU_ITEM;
SELECT * FROM RAW.RAW_MENU_ITEM LIMIT 10;

USE SCHEMA RAW;
SELECT *
FROM TABLE(
  INFORMATION_SCHEMA.COPY_HISTORY(
    TABLE_NAME => 'RAW_MENU_ITEM',
    START_TIME => DATEADD(hour,-1,CURRENT_TIMESTAMP())
);
