USE DATABASE ZOMATO_DWH;
USE SCHEMA INGESTION;

CREATE OR REPLACE PIPE pipe_payment
AS
COPY INTO RAW.RAW_PAYMENT
FROM @zomato_internal_stage/payment
FILE_FORMAT = (FORMAT_NAME = 'zomato_csv_ff')
ON_ERROR = 'CONTINUE';

ALTER PIPE pipe_payment REFRESH;

SELECT COUNT(*) FROM RAW.RAW_PAYMENT;
SELECT * FROM RAW.RAW_PAYMENT LIMIT 10;

USE SCHEMA RAW;
SELECT *
FROM TABLE(
  INFORMATION_SCHEMA.COPY_HISTORY(
    TABLE_NAME => 'RAW_PAYMENT',
    START_TIME => DATEADD(hour,-1,CURRENT_TIMESTAMP())
);
