USE DATABASE ZOMATO_DWH;
USE SCHEMA INGESTION;

CREATE OR REPLACE PIPE pipe_restaurant
AS
COPY INTO RAW.RAW_RESTAURANT
FROM @zomato_internal_stage/restaurant
FILE_FORMAT = (FORMAT_NAME = 'zomato_csv_ff')
ON_ERROR = 'CONTINUE';

ALTER PIPE pipe_restaurant REFRESH;

SELECT COUNT(*) FROM RAW.RAW_RESTAURANT;
SELECT * FROM RAW.RAW_RESTAURANT LIMIT 10;

USE SCHEMA RAW;
SELECT *
FROM TABLE(
  INFORMATION_SCHEMA.COPY_HISTORY(
    TABLE_NAME => 'RAW_RESTAURANT',
    START_TIME => DATEADD(hour,-1,CURRENT_TIMESTAMP())
);
