USE DATABASE ZOMATO_DWH;
USE SCHEMA INGESTION;

CREATE OR REPLACE PIPE pipe_order_header
AS
COPY INTO RAW.RAW_ORDER_HEADER
FROM @zomato_internal_stage/order_header
FILE_FORMAT = (FORMAT_NAME = 'zomato_csv_ff')
ON_ERROR = 'CONTINUE';

ALTER PIPE pipe_order_header REFRESH;

SELECT COUNT(*) FROM RAW.RAW_ORDER_HEADER;
SELECT * FROM RAW.RAW_ORDER_HEADER LIMIT 10;

USE SCHEMA RAW;
SELECT *
FROM TABLE(
  INFORMATION_SCHEMA.COPY_HISTORY(
    TABLE_NAME => 'RAW_ORDER_HEADER',
    START_TIME => DATEADD(hour,-1,CURRENT_TIMESTAMP())
);
