USE DATABASE ZOMATO_DWH;
USE SCHEMA INGESTION;

CREATE OR REPLACE PIPE pipe_customer_feedback
AS
COPY INTO RAW.RAW_CUSTOMER_FEEDBACK
FROM @zomato_internal_stage/customer_feedback
FILE_FORMAT = (FORMAT_NAME = 'zomato_csv_ff')
ON_ERROR = 'CONTINUE';

ALTER PIPE pipe_customer_feedback REFRESH;

SELECT COUNT(*) FROM RAW.RAW_CUSTOMER_FEEDBACK;
SELECT * FROM RAW.RAW_CUSTOMER_FEEDBACK LIMIT 10;

USE SCHEMA RAW;
SELECT *
FROM TABLE(
  INFORMATION_SCHEMA.COPY_HISTORY(
    TABLE_NAME => 'RAW_CUSTOMER_FEEDBACK',
    START_TIME => DATEADD(hour,-1,CURRENT_TIMESTAMP())
);
