---------------------------------------------------------------------------
--  ROLES & GRANTS (ACCOUNTADMIN ONLY) 
---------------------------------------------------------------------------

USE ROLE ACCOUNTADMIN;
USE DATABASE ZOMATO_DWH;

-- Create roles
CREATE ROLE IF NOT EXISTS ZOMATO_SYSADMIN;
CREATE ROLE IF NOT EXISTS ZOMATO_ANALYST;
CREATE ROLE IF NOT EXISTS ZOMATO_STATE_MANAGER;
CREATE ROLE IF NOT EXISTS ZOMATO_RESTAURANT_USER;
CREATE ROLE IF NOT EXISTS ZOMATO_PII_ADMIN_ROLE;

-- Warehouse usage
GRANT USAGE ON WAREHOUSE WH_ZOMATO TO ROLE ZOMATO_SYSADMIN;
GRANT USAGE ON WAREHOUSE WH_ZOMATO TO ROLE ZOMATO_ANALYST;
GRANT USAGE ON WAREHOUSE WH_ZOMATO TO ROLE ZOMATO_STATE_MANAGER;
GRANT USAGE ON WAREHOUSE WH_ZOMATO TO ROLE ZOMATO_RESTAURANT_USER;

-- Database usage
GRANT USAGE ON DATABASE ZOMATO_DWH TO ROLE ZOMATO_SYSADMIN;
GRANT USAGE ON DATABASE ZOMATO_DWH TO ROLE ZOMATO_ANALYST;
GRANT USAGE ON DATABASE ZOMATO_DWH TO ROLE ZOMATO_STATE_MANAGER;
GRANT USAGE ON DATABASE ZOMATO_DWH TO ROLE ZOMATO_RESTAURANT_USER;

-- Schema usage on existing schemas
GRANT USAGE ON ALL SCHEMAS IN DATABASE ZOMATO_DWH TO ROLE ZOMATO_SYSADMIN;
GRANT USAGE ON ALL SCHEMAS IN DATABASE ZOMATO_DWH TO ROLE ZOMATO_ANALYST;
GRANT USAGE ON ALL SCHEMAS IN DATABASE ZOMATO_DWH TO ROLE ZOMATO_STATE_MANAGER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE ZOMATO_DWH TO ROLE ZOMATO_RESTAURANT_USER;

-- Schema usage on future schemas
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE ZOMATO_DWH TO ROLE ZOMATO_SYSADMIN;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE ZOMATO_DWH TO ROLE ZOMATO_ANALYST;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE ZOMATO_DWH TO ROLE ZOMATO_STATE_MANAGER;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE ZOMATO_DWH TO ROLE ZOMATO_RESTAURANT_USER;

-- SELECT on MARTS
GRANT SELECT ON ALL TABLES IN SCHEMA ZOMATO_DWH.MARTS TO ROLE ZOMATO_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA ZOMATO_DWH.MARTS TO ROLE ZOMATO_STATE_MANAGER;
GRANT SELECT ON ALL TABLES IN SCHEMA ZOMATO_DWH.MARTS TO ROLE ZOMATO_RESTAURANT_USER;

-- SELECT on MARTS
GRANT SELECT ON FUTURE TABLES IN SCHEMA ZOMATO_DWH.MARTS TO ROLE ZOMATO_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ZOMATO_DWH.MARTS TO ROLE ZOMATO_STATE_MANAGER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ZOMATO_DWH.MARTS TO ROLE ZOMATO_RESTAURANT_USER;

-- SELECT on INT
GRANT SELECT ON ALL TABLES IN SCHEMA ZOMATO_DWH.INT TO ROLE ZOMATO_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA ZOMATO_DWH.INT TO ROLE ZOMATO_STATE_MANAGER;
GRANT SELECT ON ALL TABLES IN SCHEMA ZOMATO_DWH.INT TO ROLE ZOMATO_RESTAURANT_USER;

-- Security-related grants (account-level)
GRANT APPLY MASKING POLICY ON ACCOUNT TO ROLE ZOMATO_PII_ADMIN_ROLE;
GRANT APPLY ROW ACCESS POLICY ON ACCOUNT TO ROLE ZOMATO_SYSADMIN;
