USE ROLE ACCOUNTADMIN;
USE DATABASE ZOMATO_DWH;
USE SCHEMA MARTS;

CREATE OR REPLACE TABLE FCT_ORDER_SECURE (
  ORDER_ID             NUMBER,
  ORDER_DATE_KEY       NUMBER,
  FULL_DATE            DATE,
  TOTAL_AMOUNT         NUMBER(12,2),
  ORDER_SUBTOTAL       NUMBER(12,2),
  ORDER_DISCOUNT       NUMBER(12,2),
  DELIVERY_FEE         NUMBER(10,2),
  NET_FOOD_AMOUNT      NUMBER(12,2),
  DISCOUNT_PCT         FLOAT,
  SLA_BREACHED         NUMBER,
  PLATFORM_COMMISSION  NUMBER(12,2),
  RESTAURANT_PAYOUT    NUMBER(12,2),
  END_TO_END_MIN       NUMBER,
  ORDER_STATUS         STRING,
  PAYMENT_METHOD       STRING,
  PROMO_ID             NUMBER,
  IS_DELIVERED         NUMBER,
  IS_CANCELLED         NUMBER,
  CUSTOMER_ID          NUMBER,
  CUSTOMER_NAME        STRING,
  CUSTOMER_CITY        STRING,
  CUSTOMER_AREA        STRING,
  CUSTOMER_SEGMENT     STRING,
  RESTAURANT_ID        NUMBER,
  RESTAURANT_NAME      STRING,
  RESTAURANT_CITY      STRING,
  RESTAURANT_AREA      STRING,
  CUISINE_PRIMARY      STRING,
  COMMISSION_RATE      FLOAT,
  DISTANCE_KM          NUMBER(10,2),
  SLA_BREACH_FLAG      NUMBER,
  RATING               NUMBER,
  SENTIMENT_SCORE      FLOAT
);

USE ROLE ACCOUNTADMIN;
USE DATABASE ZOMATO_DWH;
USE SCHEMA UTIL;

CREATE OR REPLACE PROCEDURE SP_REFRESH_FCT_ORDER_SECURE()
RETURNS STRING
LANGUAGE JAVASCRIPT
EXECUTE AS CALLER
AS
$$
  try {
    snowflake.execute({sqlText: 'BEGIN'});

    snowflake.execute({sqlText: 'TRUNCATE TABLE MARTS.FCT_ORDER_SECURE'});

    var sql = `
      INSERT INTO MARTS.FCT_ORDER_SECURE (
        ORDER_ID,
        ORDER_DATE_KEY,
        FULL_DATE,
        TOTAL_AMOUNT,
        ORDER_SUBTOTAL,
        ORDER_DISCOUNT,
        DELIVERY_FEE,
        NET_FOOD_AMOUNT,
        DISCOUNT_PCT,
        SLA_BREACHED,
        PLATFORM_COMMISSION,
        RESTAURANT_PAYOUT,
        END_TO_END_MIN,
        ORDER_STATUS,
        PAYMENT_METHOD,
        PROMO_ID,
        IS_DELIVERED,
        IS_CANCELLED,
        CUSTOMER_ID,
        CUSTOMER_NAME,
        CUSTOMER_CITY,
        CUSTOMER_AREA,
        CUSTOMER_SEGMENT,
        RESTAURANT_ID,
        RESTAURANT_NAME,
        RESTAURANT_CITY,
        RESTAURANT_AREA,
        CUISINE_PRIMARY,
        COMMISSION_RATE,
        DISTANCE_KM,
        SLA_BREACH_FLAG,
        RATING,
        SENTIMENT_SCORE
      )
      SELECT
        ORDER_ID,
        ORDER_DATE_KEY,
        FULL_DATE,
        TOTAL_AMOUNT,
        ORDER_SUBTOTAL,
        ORDER_DISCOUNT,
        DELIVERY_FEE,
        NET_FOOD_AMOUNT,
        DISCOUNT_PCT,
        SLA_BREACHED,
        PLATFORM_COMMISSION,
        RESTAURANT_PAYOUT,
        END_TO_END_MIN,
        ORDER_STATUS,
        PAYMENT_METHOD,
        PROMO_ID,
        IS_DELIVERED,
        IS_CANCELLED,
        CUSTOMER_ID,
        CUSTOMER_NAME,
        CUSTOMER_CITY,
        CUSTOMER_AREA,
        CUSTOMER_SEGMENT,
        RESTAURANT_ID,
        RESTAURANT_NAME,
        RESTAURANT_CITY,
        RESTAURANT_AREA,
        CUISINE_PRIMARY,
        COMMISSION_RATE,
        DISTANCE_KM,
        SLA_BREACH_FLAG,
        RATING,
        SENTIMENT_SCORE
      FROM MARTS.V_ORDER_ENRICHED
    `;
    snowflake.execute({sqlText: sql});

    snowflake.execute({sqlText: `
      INSERT INTO UTIL.PROC_AUDIT_LOG(PROC_NAME,RUN_TS,STATUS,MESSAGE)
      VALUES ('SP_REFRESH_FCT_ORDER_SECURE', CURRENT_TIMESTAMP(), 'SUCCESS', 'FCT_ORDER_SECURE refreshed')
    `});

    snowflake.execute({sqlText: 'COMMIT'});
    return 'FCT_ORDER_SECURE refreshed successfully';
  } catch (err) {
    try { snowflake.execute({sqlText: 'ROLLBACK'}); } catch (e2) {}
    snowflake.execute({
      sqlText: `
        INSERT INTO UTIL.PROC_AUDIT_LOG(PROC_NAME,RUN_TS,STATUS,MESSAGE)
        VALUES ('SP_REFRESH_FCT_ORDER_SECURE', CURRENT_TIMESTAMP(), 'ERROR', :msg)
      `,
      binds: { msg: err.toString() }
    });
    return 'ERROR in SP_REFRESH_FCT_ORDER_SECURE: ' + err;
  }
$$;

-- Initial load (you can re-run anytime)
CALL UTIL.SP_REFRESH_FCT_ORDER_SECURE();


--Prerequisites:
USE ROLE ACCOUNTADMIN;
USE DATABASE ZOMATO_DWH;

-- Make sure secure fact is loaded
CALL UTIL.SP_REFRESH_FCT_ORDER_SECURE();

-- Quick sanity check 
SELECT RESTAURANT_CITY, RESTAURANT_ID, COUNT(*) AS ORDER_CNT
FROM MARTS.FCT_ORDER_SECURE
GROUP BY 1,2
ORDER BY 1,2;

USE ROLE ACCOUNTADMIN;
USE DATABASE ZOMATO_DWH;
USE SCHEMA MARTS;

BEGIN
  ALTER TABLE FCT_ORDER_SECURE
    DROP ROW ACCESS POLICY UTIL.RLP_MARTS_CITY_RESTAURANT;
EXCEPTION
  WHEN OTHER THEN
    -- do nothing if policy not attached
    NULL;
END;

-- (Re-)create mapping table in UTIL schema
USE SCHEMA UTIL;

CREATE OR REPLACE TABLE RLS_ROLE_ACCESS (
  ROLE_NAME     STRING,
  ACCESS_TYPE   STRING,      -- 'CITY' or 'RESTAURANT'
  CITY          STRING,
  RESTAURANT_ID NUMBER
);


INSERT INTO RLS_ROLE_ACCESS (ROLE_NAME, ACCESS_TYPE, CITY, RESTAURANT_ID) VALUES
  -- State managers (city-based access)
  ('ZOMATO_STATE_MANAGER_BLR',   'CITY',       'Bengaluru', NULL),
  ('ZOMATO_STATE_MANAGER_MUMBAI','CITY',       'Mumbai',    NULL),

  -- Restaurant-specific roles (single restaurant)
  ('ZOMATO_RESTAURANT_R100',     'RESTAURANT', NULL,        100),
  ('ZOMATO_RESTAURANT_R200',     'RESTAURANT', NULL,        200);

USE ROLE ACCOUNTADMIN;
USE DATABASE ZOMATO_DWH;

-- Parent "functional" roles if not already created
CREATE ROLE IF NOT EXISTS ZOMATO_SYSADMIN;
CREATE ROLE IF NOT EXISTS ZOMATO_ANALYST;

-- Demo RLS roles
CREATE ROLE IF NOT EXISTS ZOMATO_STATE_MANAGER_BLR;
CREATE ROLE IF NOT EXISTS ZOMATO_STATE_MANAGER_MUMBAI;
CREATE ROLE IF NOT EXISTS ZOMATO_RESTAURANT_R100;
CREATE ROLE IF NOT EXISTS ZOMATO_RESTAURANT_R200;

-- Give these roles access to warehouse + MARTS schema
GRANT USAGE ON WAREHOUSE WH_ZOMATO TO ROLE ZOMATO_STATE_MANAGER_BLR;
GRANT USAGE ON WAREHOUSE WH_ZOMATO TO ROLE ZOMATO_STATE_MANAGER_MUMBAI;
GRANT USAGE ON WAREHOUSE WH_ZOMATO TO ROLE ZOMATO_RESTAURANT_R100;
GRANT USAGE ON WAREHOUSE WH_ZOMATO TO ROLE ZOMATO_RESTAURANT_R200;

GRANT USAGE ON DATABASE ZOMATO_DWH TO ROLE ZOMATO_STATE_MANAGER_BLR;
GRANT USAGE ON DATABASE ZOMATO_DWH TO ROLE ZOMATO_STATE_MANAGER_MUMBAI;
GRANT USAGE ON DATABASE ZOMATO_DWH TO ROLE ZOMATO_RESTAURANT_R100;
GRANT USAGE ON DATABASE ZOMATO_DWH TO ROLE ZOMATO_RESTAURANT_R200;

GRANT USAGE ON SCHEMA ZOMATO_DWH.MARTS TO ROLE ZOMATO_STATE_MANAGER_BLR;
GRANT USAGE ON SCHEMA ZOMATO_DWH.MARTS TO ROLE ZOMATO_STATE_MANAGER_MUMBAI;
GRANT USAGE ON SCHEMA ZOMATO_DWH.MARTS TO ROLE ZOMATO_RESTAURANT_R100;
GRANT USAGE ON SCHEMA ZOMATO_DWH.MARTS TO ROLE ZOMATO_RESTAURANT_R200;

GRANT SELECT ON TABLE ZOMATO_DWH.MARTS.FCT_ORDER_SECURE
       TO ROLE ZOMATO_STATE_MANAGER_BLR;
GRANT SELECT ON TABLE ZOMATO_DWH.MARTS.FCT_ORDER_SECURE
       TO ROLE ZOMATO_STATE_MANAGER_MUMBAI;
GRANT SELECT ON TABLE ZOMATO_DWH.MARTS.FCT_ORDER_SECURE
       TO ROLE ZOMATO_RESTAURANT_R100;
GRANT SELECT ON TABLE ZOMATO_DWH.MARTS.FCT_ORDER_SECURE
       TO ROLE ZOMATO_RESTAURANT_R200;

CREATE OR REPLACE USER U_STATE_BLR
  PASSWORD = 'Pass@123'
  DEFAULT_ROLE = ZOMATO_STATE_MANAGER_BLR
  MUST_CHANGE_PASSWORD = FALSE;

CREATE OR REPLACE USER U_STATE_MUMBAI
  PASSWORD = 'Pass@123'
  DEFAULT_ROLE = ZOMATO_STATE_MANAGER_MUMBAI
  MUST_CHANGE_PASSWORD = FALSE;

CREATE OR REPLACE USER U_REST_R100
  PASSWORD = 'Pass@123'
  DEFAULT_ROLE = ZOMATO_RESTAURANT_R100
  MUST_CHANGE_PASSWORD = FALSE;

CREATE OR REPLACE USER U_REST_R200
  PASSWORD = 'Pass@123'
  DEFAULT_ROLE = ZOMATO_RESTAURANT_R200
  MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE ZOMATO_STATE_MANAGER_BLR    TO USER U_STATE_BLR;
GRANT ROLE ZOMATO_STATE_MANAGER_MUMBAI TO USER U_STATE_MUMBAI;
GRANT ROLE ZOMATO_RESTAURANT_R100      TO USER U_REST_R100;
GRANT ROLE ZOMATO_RESTAURANT_R200      TO USER U_REST_R200;

GRANT ROLE ZOMATO_STATE_MANAGER_BLR    TO ROLE ACCOUNTADMIN;
GRANT ROLE ZOMATO_STATE_MANAGER_MUMBAI TO ROLE ACCOUNTADMIN;
GRANT ROLE ZOMATO_RESTAURANT_R100      TO ROLE ACCOUNTADMIN;
GRANT ROLE ZOMATO_RESTAURANT_R200      TO ROLE ACCOUNTADMIN;


USE ROLE ACCOUNTADMIN;
USE DATABASE ZOMATO_DWH;
USE SCHEMA UTIL;

CREATE OR REPLACE ROW ACCESS POLICY RLP_MARTS_CITY_RESTAURANT
AS (RESTAURANT_CITY STRING, RESTAURANT_ID NUMBER) RETURNS BOOLEAN ->
  CASE
    -- Admin/system roles see everything
    WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'ZOMATO_SYSADMIN') THEN TRUE

    -- For other roles, check mapping table
    ELSE EXISTS (
      SELECT 1
      FROM UTIL.RLS_ROLE_ACCESS r
      WHERE r.ROLE_NAME = CURRENT_ROLE()
        AND (
             (r.ACCESS_TYPE = 'CITY'
              AND r.CITY = RESTAURANT_CITY)
          OR (r.ACCESS_TYPE = 'RESTAURANT'
              AND r.RESTAURANT_ID = RESTAURANT_ID)
        )
    )
  END;


USE ROLE ACCOUNTADMIN;
USE DATABASE ZOMATO_DWH;
USE SCHEMA MARTS;

ALTER TABLE FCT_ORDER_SECURE
  ADD ROW ACCESS POLICY UTIL.RLP_MARTS_CITY_RESTAURANT
  ON (RESTAURANT_CITY, RESTAURANT_ID);

USE SECONDARY ROLES NONE;
USE ROLE ZOMATO_STATE_MANAGER_BLR;
USE WAREHOUSE WH_ZOMATO;
SELECT * FROM MARTS.FCT_ORDER_SECURE;
  
USE SECONDARY ROLES NONE;
USE ROLE ZOMATO_STATE_MANAGER_MUMBAI;
USE WAREHOUSE WH_ZOMATO;
SELECT * FROM MARTS.FCT_ORDER_SECURE;

USE SECONDARY ROLES NONE;
USE ROLE ZOMATO_RESTAURANT_R100;
USE WAREHOUSE WH_ZOMATO;
SELECT * FROM MARTS.FCT_ORDER_SECURE;

USE SECONDARY ROLES NONE;
USE ROLE ZOMATO_RESTAURANT_R200;
USE WAREHOUSE WH_ZOMATO;
SELECT * FROM MARTS.FCT_ORDER_SECURE;
