USE DATABASE ZOMATO_DWH;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE PAYMENT_RAW (
  PAYMENT_ID         STRING,
  ORDER_ID           STRING,
  PAYMENT_STATUS     STRING,
  PAYMENT_AT         STRING,
  PAYMENT_AMOUNT     STRING
);
