USE DATABASE ZOMATO_DWH;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE PROMOTION_RAW (
  PROMO_ID           STRING,
  PROMO_CODE         STRING,
  DISCOUNT_PERCENT   STRING,
  START_DATE         STRING,
  END_DATE           STRING,
  MAX_DISCOUNT_AMT   STRING,
  TARGET_SEGMENT     STRING,
  TARGET_CITY        STRING
);

