USE SCHEMA RAW;

CREATE OR REPLACE TABLE RAW_CUSTOMER (
  CUSTOMER_ID        STRING,
  CUSTOMER_NAME      STRING,
  EMAIL              STRING,
  PRIMARY_PHONE      STRING,
  REGISTERED_AT      STRING,
  CITY               STRING,
  AREA               STRING,
  LAT                STRING,
  LNG                STRING,
  SEGMENT            STRING,
  IS_PRIME_MEMBER    STRING,
  STATUS             STRING
);
