USE DATABASE ZOMATO_DWH;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE ORDER_HEADER_RAW (
  ORDER_ID             STRING,
  CUSTOMER_ID          STRING,
  RESTAURANT_ID        STRING,
  ORDER_CREATED_AT     STRING,
  ORDER_STATUS         STRING,
  PAYMENT_METHOD       STRING,
  PROMO_ID             STRING,
  ORDER_SUBTOTAL       STRING,
  ORDER_DISCOUNT       STRING,
  DELIVERY_FEE         STRING,
  TOTAL_AMOUNT         STRING,
  EXPECTED_DELIVERY_AT STRING,
  ACTUAL_DELIVERY_AT   STRING,
  CANCELLATION_REASON  STRING
);