USE SCHEMA RAW;

CREATE OR REPLACE TABLE RAW_RESTAURANT (
  RESTAURANT_ID      STRING,
  RESTAURANT_NAME    STRING,
  CUISINE_PRIMARY    STRING,
  CUISINE_SECONDARY  STRING,
  CITY               STRING,
  AREA               STRING,
  LAT                STRING,
  LNG                STRING,
  AVG_RATING         STRING,
  COMMISSION_RATE    STRING,
  IS_ACTIVE          STRING,
  ONBOARDED_AT       STRING
);
