USE SCHEMA RAW;

CREATE OR REPLACE TABLE RAW_ORDER_ITEM (
  ORDER_ID           STRING,
  ORDER_ITEM_ID      STRING,
  MENU_ITEM_ID       STRING,
  QTY                STRING,
  ITEM_PRICE         STRING,
  ITEM_DISCOUNT      STRING,
  TOTAL_ITEM_AMOUNT  STRING
);
