USE DATABASE ZOMATO_DWH;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE CUSTOMER_FEEDBACK_RAW (
  FEEDBACK_ID        STRING,
  ORDER_ID           STRING,
  CUSTOMER_ID        STRING,
  RATING             STRING,
  COMMENT            STRING,
  SENTIMENT_SCORE    STRING,
  CREATED_AT         STRING
);

