USE SCHEMA RAW;

CREATE OR REPLACE TABLE RAW_DELIVERY_TRAP (
  TRIP_ID            STRING,
  ORDER_ID           STRING,
  AGENT_ID           STRING,
  PICKUP_TIME        STRING,
  DROP_TIME          STRING,
  DISTANCE_KM        STRING,
  ESTIMATED_TIME_MIN STRING,
  ACTUAL_TIME_MIN    STRING,
  SLA_BREACH_FLAG    STRING
);
