USE SCHEMA RAW;

CREATE OR REPLACE TABLE RAW_MENU_ITEM (
  MENU_ITEM_ID       STRING,
  RESTAURANT_ID      STRING,
  ITEM_NAME          STRING,
  CATEGORY           STRING,
  PRICE              STRING,
  IS_VEG             STRING,
  IS_ACTIVE          STRING
);
