USE SCHEMA RAW;

CREATE OR REPLACE TABLE RAW_CUSTOMER_FEEDBACK (
  FEEDBACK_ID        STRING,
  ORDER_ID           STRING,
  CUSTOMER_ID        STRING,
  RATING             STRING,
  COMMENT            STRING,
  SENTIMENT_SCORE    STRING,
  CREATED_AT         STRING
);
