USE SCHEMA RAW;

CREATE OR REPLACE TABLE RAW_PAYMENT (
  PAYMENT_ID         STRING,
  ORDER_ID           STRING,
  PAYMENT_STATUS     STRING,
  PAYMENT_AT         STRING,
  PAYMENT_AMOUNT     STRING
);
