USE ROLE ACCOUNTADMIN;
USE DATABASE ZOMATO_DWH;
USE SCHEMA INT;

CREATE OR REPLACE TASK TASK_LOAD_FACTS
  WAREHOUSE = WH_ZOMATO
  SCHEDULE  = 'USING CRON 15 * * * * Asia/Kolkata'
AS
BEGIN
  CALL UTIL.SP_LOAD_FCT_ORDER_ENHANCED();
  CALL UTIL.SP_LOAD_FCT_DELIVERY();
  CALL UTIL.SP_LOAD_FCT_FEEDBACK();
  CALL UTIL.SP_LOAD_FCT_CUSTOMER_EVENT();
END;

ALTER TASK TASK_LOAD_FACTS RESUME;
