USE ROLE ACCOUNTADMIN;
USE DATABASE ZOMATO_DWH;
USE SCHEMA INT;

CREATE OR REPLACE TASK TASK_LOAD_DIMS
  WAREHOUSE = WH_ZOMATO
  SCHEDULE  = 'USING CRON 0 * * * * Asia/Kolkata'
AS
BEGIN
  CALL UTIL.SP_LOAD_DIM_CUSTOMER_SCD2();
  CALL UTIL.SP_LOAD_DIM_RESTAURANT_SCD2();
  CALL UTIL.SP_LOAD_DIM_RESTAURANT_SCD3();
  CALL UTIL.SP_LOAD_DIM_DELIVERY_AGENT();
  CALL UTIL.SP_LOAD_DIM_PROMOTION();
END;

ALTER TASK TASK_LOAD_DIMS RESUME;
